language: objective-c
osx_image: xcode7.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - gem install cocoapods --no-document --pre --quiet
  - cd Example; pod update ; cd ..
xcode_workspace: Example/ARAnalyticsTests.xcworkspace
xcode_scheme: ARAnalyticsBootstrapiOS
xcode_sdk: iphonesimulator